version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ingestion_engine_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: ingestion_engine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
